// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	ID        string
	UserID    int32
	Email     string
	ExpiresAt pgtype.Timestamptz
}

type Project struct {
	ID                 int32
	Uuid               pgtype.UUID
	Name               string
	UserID             int32
	QrBackground       string
	QrForeground       string
	CustomDomain       pgtype.Text
	DomainStatus       string
	EnableCustomDomain bool
	CustomIp           pgtype.Text
	CustomDomainID     pgtype.Text
}

type Session struct {
	ID        string
	UserID    int32
	ExpiresAt pgtype.Timestamptz
}

type Setting struct {
	UserID       int32
	QrBackground pgtype.Text
	QrForeground pgtype.Text
}

type Shortener struct {
	ID          int32
	Link        string
	Code        string
	CreatedAt   pgtype.Timestamp
	UserID      int32
	ProjectID   pgtype.Int4
	Active      bool
	Ios         bool
	IosLink     pgtype.Text
	Android     bool
	AndroidLink pgtype.Text
}

type User struct {
	ID            int32
	Uuid          pgtype.UUID
	Email         string
	Username      pgtype.Text
	Password      string
	CreatedAt     pgtype.Timestamp
	EmailVerified bool
}

type Visitor struct {
	ID           int32
	ShortenerID  int32
	CreatedAt    pgtype.Timestamp
	CountryCode  string
	Country      string
	City         string
	DeviceType   string
	DeviceVendor string
	Os           string
	Browser      string
}
