# fly.toml app configuration file generated for geolite2 on 2024-08-04T12:09:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'geolite2'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.22.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
